version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo
    container_name: mongodb-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

  # NestJS application service
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-container
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      MONGO_URL: ${MONGO_URL}
